<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>QuantConnect.DataSource.MetaTrader</RootNamespace>
    <AssemblyName>QuantConnect.DataSource.MetaTrader.MyCustomDataType</AssemblyName>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <DocumentationFile>$(OutputPath)\QuantConnect.DataSource.MetaTrader.MyCustomDataType.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\QuantConnect.Lean.Engine.csproj" />
    <ProjectReference Include="..\Common\QuantConnect.csproj" />
    <PackageReference Include="protobuf-net" Version="3.1.33" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
    <None Remove="tests\**" />
    <Compile Remove="DataProcessing\**" />
    <EmbeddedResource Remove="DataProcessing\**" />
    <None Remove="DataProcessing\**" />
    <Compile Remove="Demonstration.cs" />
    <Compile Remove="DemonstrationUniverse.cs" />
    <None Remove=".gitignore" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\MtProxyUI\MT\MT.csproj" />
  </ItemGroup>
</Project>
